// <auto-generated />
using System;
using GerenciaServidoresAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciaServidoresAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GerenciaServidoresAPI.Domain.Entities.Lotacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lotacoes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-111111111111"),
                            Nome = "Hospital Municipal"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Nome = "Escola Estadual"
                        });
                });

            modelBuilder.Entity("GerenciaServidoresAPI.Domain.Entities.Orgao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orgaos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Nome = "Secretaria de Saúde"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-222222222222"),
                            Nome = "Secretaria de Educação"
                        });
                });

            modelBuilder.Entity("GerenciaServidoresAPI.Domain.Entities.Servidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LotacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrgaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sala")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LotacaoId");

                    b.HasIndex("OrgaoId");

                    b.ToTable("Servidores");
                });

            modelBuilder.Entity("GerenciaServidoresAPI.Domain.Entities.Servidor", b =>
                {
                    b.HasOne("GerenciaServidoresAPI.Domain.Entities.Lotacao", "Lotacao")
                        .WithMany("Servidores")
                        .HasForeignKey("LotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciaServidoresAPI.Domain.Entities.Orgao", "Orgao")
                        .WithMany("Servidores")
                        .HasForeignKey("OrgaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lotacao");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("GerenciaServidoresAPI.Domain.Entities.Lotacao", b =>
                {
                    b.Navigation("Servidores");
                });

            modelBuilder.Entity("GerenciaServidoresAPI.Domain.Entities.Orgao", b =>
                {
                    b.Navigation("Servidores");
                });
#pragma warning restore 612, 618
        }
    }
}
